// <auto-generated />
using System;
using Aldaris.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aldaris.API.Migrations
{
    [DbContext(typeof(AldarisContext))]
    [Migration("20221113091517_AddOrginallySuggestedAnswerField")]
    partial class AddOrginallySuggestedAnswerField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aldaris.API.Domain.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClauseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClauseValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Aldaris.API.Domain.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameStage")
                        .HasColumnType("int");

                    b.Property<string>("OriginallySupposedSolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("Aldaris.API.Domain.GameSessionAnswer", b =>
                {
                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("AnswerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AskedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GameSessionId", "QuestionId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("GameSessionAnswer");
                });

            modelBuilder.Entity("Aldaris.API.Domain.KnowledgeBaseFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Facts");
                });

            modelBuilder.Entity("Aldaris.API.Domain.KnowledgeBaseRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsequentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsequentId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("Aldaris.API.Domain.KnowledgeBaseRuleAntecedent", b =>
                {
                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.Property<int>("AntecedentId")
                        .HasColumnType("int");

                    b.HasKey("RuleId", "AntecedentId");

                    b.HasIndex("AntecedentId");

                    b.ToTable("KnowledgeBaseRuleAntecedent");
                });

            modelBuilder.Entity("Aldaris.API.Domain.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Aldaris.API.Domain.QuestionPossibleAnswer", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId", "AnswerId");

                    b.HasIndex("AnswerId");

                    b.ToTable("QuestionPossibleAnswer");
                });

            modelBuilder.Entity("Aldaris.API.Domain.GameSessionAnswer", b =>
                {
                    b.HasOne("Aldaris.API.Domain.Answer", "Answer")
                        .WithMany("GameSessionAnswers")
                        .HasForeignKey("AnswerId");

                    b.HasOne("Aldaris.API.Domain.GameSession", "GameSession")
                        .WithMany("GameSessionAnswers")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aldaris.API.Domain.Question", "Question")
                        .WithMany("GameSessionAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("GameSession");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Aldaris.API.Domain.KnowledgeBaseRule", b =>
                {
                    b.HasOne("Aldaris.API.Domain.KnowledgeBaseFact", "Consequent")
                        .WithMany()
                        .HasForeignKey("ConsequentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consequent");
                });

            modelBuilder.Entity("Aldaris.API.Domain.KnowledgeBaseRuleAntecedent", b =>
                {
                    b.HasOne("Aldaris.API.Domain.KnowledgeBaseFact", "Antecedent")
                        .WithMany()
                        .HasForeignKey("AntecedentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Aldaris.API.Domain.KnowledgeBaseRule", "Rule")
                        .WithMany("KnowledgeBaseRuleAntecedents")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Antecedent");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Aldaris.API.Domain.QuestionPossibleAnswer", b =>
                {
                    b.HasOne("Aldaris.API.Domain.Answer", "Answer")
                        .WithMany("QuestionPossibleAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aldaris.API.Domain.Question", "Question")
                        .WithMany("QuestionPossibleAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Aldaris.API.Domain.Answer", b =>
                {
                    b.Navigation("GameSessionAnswers");

                    b.Navigation("QuestionPossibleAnswers");
                });

            modelBuilder.Entity("Aldaris.API.Domain.GameSession", b =>
                {
                    b.Navigation("GameSessionAnswers");
                });

            modelBuilder.Entity("Aldaris.API.Domain.KnowledgeBaseRule", b =>
                {
                    b.Navigation("KnowledgeBaseRuleAntecedents");
                });

            modelBuilder.Entity("Aldaris.API.Domain.Question", b =>
                {
                    b.Navigation("GameSessionAnswers");

                    b.Navigation("QuestionPossibleAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
